AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This project implements a serverless, event-driven data engineering pipeline on AWS.
  The pipeline automatically ingests raw data files uploaded to Amazon S3.  

Parameters:

  ProjectName:
    Type: String
    Default: s3-to-s3-glue

  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
    Default: dev

  Owner:
    Type: String
    Default: storm-data-engineer

  GlueJobName:
    Type: String
    Default: storm-s3-parquet-job

  GlueRoleArn:
    Type: String
    Description: Existing IAM Role ARN for Glue
    Default: arn:aws:iam::297041784012:role/Glue-service-role

  GlueScriptS3Path:
    Type: String
    Default: s3://storm-glue-scripts-2026/scripts/s3_to_s3_copy.py

  SourceS3Path:
    Type: String
    Default: s3://storm-source-data-dumps-2026/sample_data/landing_zone_data/

  SourcePrefix:
    Type: String
    Default: sample_data/landing_zone_data/

  TargetS3Path:
    Type: String
    Default: s3://storm-source-data-dumps-2026/sample_data/derived_data/

Resources:

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !Ref GlueRoleArn

      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 60
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1

      Command:
        Name: glueetl
        ScriptLocation: !Ref GlueScriptS3Path
        PythonVersion: "3"

      DefaultArguments:
        "--job-language": python
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"

        "--SOURCE_S3_PATH": !Ref SourceS3Path
        "--TARGET_S3_PATH": !Ref TargetS3Path
        "--ENV": !Ref Environment
        "--PROJECT": !Ref ProjectName
        "--OWNER": !Ref Owner

      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment
        Owner: !Ref Owner
        Service: Glue
        DataFlow: S3-to-Parquet

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Sub ${ProjectName}-Workflow-${Environment}

  GlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub ${ProjectName}-S3Trigger
      Type: EVENT
      WorkflowName: !Ref GlueWorkflow
      Actions:
        - JobName: !Ref GlueJobName
      EventBatchingCondition:
        BatchSize: 1
        BatchWindow: 5
      Description: Trigger Glue job when files arrive in S3
    DependsOn: GlueJob

Outputs:

  GlueJobName:
    Description: Glue Job Name
    Value: !Ref GlueJob

  GlueScriptPath:
    Description: Glue script S3 path
    Value: !Ref GlueScriptS3Path

  SourcePath:
    Description: Source S3 data path
    Value: !Ref SourceS3Path

  TargetPath:
    Description: Target S3 data path
    Value: !Ref TargetS3Path